### ISSUE TITLE
A little question about how the official doc write onClick

### ISSUE THREAD

**Issue by Cifer-Y** [the-road-to-learn-react/react-alternative-class-component-syntax#3]
I noticed the official doc use closure to avoid binding `this` in the constructor.
In the book, we did this
```javascript
import React, {Component} from 'react';

class ExplainBinding extends Component {

  constructor(props) {
    super(props);
    this.handleClick = this.handleClick.bind(this);
  }


  handleClick() {
    console.log(this);
  }
  render() {
    return (
      <button
        type="button"
        onClick={this.handleClick}
      >
        Click Me
      </button>
    )
  }
}

export default ExplainBinding;
```

And in the official doc, I found this
```javascript
import React, {Component} from 'react';

class ExplainBinding extends Component {

  constructor(props) {
    super(props);
    // this.handleClick = this.handleClick.bind(this);
  }


  handleClick() {
    console.log(this);
  }
  render() {
    return (
      <button
        type="button"
        onClick={() => this.handleClick()} // there is a closure
      >
        Click Me
      </button>
    )
  }
}

export default ExplainBinding;
```

So I want to know if the official doc way is a better way or a recommended way?

**Comment by dagolinuxoid** [comment]
@Cifer-Y, the first snippet is a preferred way to handle `this` when you're decided to use class components at the moment (it's not a big of a deal though, for example I prefer to use public fields and put arrow functions in them). Take a look at [react official docs](https://reactjs.org/docs/handling-events.html);

**Comment by omega-station** [comment]
fooofoof

**Comment by dagolinuxoid** [comment]
Update: starting at v16.8 there is no need to use classes since functional components provide necessary functionality via hooks.

**Comment by omega-station** [comment]
This is a new comment!
